# https://mcr.microsoft.com/en-us/artifact/mar/dotnet/samples/tags
FROM mcr.microsoft.com/dotnet/samples:aspnetapp-8.0 
# The base image no longer has trimming enabled by default so we can use it again
# this image still exists for backwards compatibility with docs/examples