# https://mcr.microsoft.com/en-us/artifact/mar/dotnet/samples/tags
FROM mcr.microsoft.com/dotnet/samples:aspnetapp-8.0@sha256:4682284c8c2f87d426ff2ee27319705af02620e36e486b450ab080d9c83cbad9 
# The base image no longer has trimming enabled by default so we can use it again
# this image still exists for backwards compatibility with docs/examples