name: "Sample Apps Build"
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker:
    strategy:
      matrix:
        variants:
        - type: aspnetcore
          dockerfile: "src/aspnetcore/Dockerfile"
          context: "src/aspnetcore"
          platforms: "linux/amd64,linux/arm64"
        - type: fastify-esm
          dockerfile: "src/fastify-esm/Dockerfile"
          context: "src/fastify-esm"
          platforms: "linux/amd64,linux/arm64"
        - type: flask
          dockerfile: "src/flask/Dockerfile"
          context: "src/flask"
          platforms: "linux/amd64,linux/arm64"
        - type: php
          dockerfile: "src/php/Dockerfile"
          context: "src/php"
          platforms: "linux/amd64,linux/arm64"
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: step-security/setup-qemu-action@109c6ed9f089be1a250c75fd6a534e30df44e030 # v4.0.0
        with:
          platforms: arm64
      - uses: step-security/setup-buildx-action@f931205d68723ad9589fd2a7e2ece238bf9de341 # v4.0.0
        with:
          install: true
          version: latest
      - name: Login (Dockerhub)
        uses: step-security/docker-login-action@870af644803bf9f204aed474adbad2958fec048b # v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4.6.0
        with:
          images: docker.io/contrast/sample-app-${{ matrix.variants.type }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
      - name: Build and push
        uses: step-security/docker-build-push-action@846549baaf047e867d038826129a64d81df0f704 # v7.1.0
        with:
          platforms: ${{ matrix.variants.platforms }}
          file: ${{ matrix.variants.dockerfile }}
          context: ${{ matrix.variants.context }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
